apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-service
  namespace: default
  labels:
    app: brain-tasks-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
